Fix custom queue instructions in README
When instantiating a Scheduler with a custom RQ Queue as per the README,
it fails with:

    rq.connections.NoRedisConnectionException: Could not resolve a Redis connection

This change adds the explicit `connection` attribute required to use a custom
queue.

fixes #228